FROM node:16.13.0-alpine AS builder

WORKDIR /src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build


FROM node:16.13.0-alpine

ENV NODE_ENV development

WORKDIR /src/app

COPY --from=builder /src/app ./

CMD ["npm", "run", "start:dev"]