version: '3.5'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    container_name: lotto-service-development
    env_file:
    - .env.dev
    command: npm run start:dev
    ports:
      - 8002:8002
    restart: 'always'

